# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L3r09MJczyCeaRLfwmGHewZLuR6pEsXd
"""

#indexing
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[2])



#slicing
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[1:4:1])

#Fancy indexing
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[[0,1,3]])

#Boolean masking
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[arr>30])

#reshaping
import numpy as np
arr=np.array([10,20,30,40,50,60])
reshape_arr=arr.reshape(2,3)
print(reshape_arr)

#insert function
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr)
print(np.insert(arr,4,80,axis=None))

import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr)
print(np.append(arr,[70,80]))